plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.mod_version
group = 'dev.anthonyw.distantfrontiers'

base {
    archivesName = 'distantfrontiers'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = project.neo_version

    runs {
        server {
            server()
        }
        client {
            client()
        }
    }

    mods {
        distantfrontiers {
            sourceSet sourceSets.main
        }
    }
}
